### ISSUE TITLE
Polyglot froze up PkgEval

### ISSUE THREAD

**Issue by IainNZ** [wavexx/Polyglot.jl#1] opened 2015-07-10 16:37 UTC
On 0.3 and 0.4

```
Julia Version 0.4.0-dev+5846
Commit 0503f2a (2015-07-08 02:04 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing Polyglot
bond_basic ... ERROR (unhandled task failure): readcb: i/o error (EIO)
 in yieldto at ./task.jl:21
 in wait at ./task.jl:309
 in wait at ./task.jl:225
 in wait_readnb at ./stream.jl:359
 in anonymous at task.jl:160
FAIL: LoadError("/home/vagrant/.julia/v0.4/Polyglot/test/test_bond_basic.jl",26,Polyglot.BondException("cannot get an interactive prompt using: ssh localhost python -i"))
bond_output ... OK
bond_size ... OK
bond_stack ... FAIL: LoadError("/home/vagrant/.julia/v0.4/Polyglot/test/test_bond_stack.jl",21,Base.Test.Error(:(bond_stack_depth(py) == 1),Expect.ExpectEOF(),[Ptr{Void} @0x00007f37cd003c95,Ptr{Void} @0x00007f37cd00425d,Ptr{Void} @0x00007f37cd004359,Ptr{Void} @0x00007f35c882070b,Ptr{Void} @0x00007f35c881f9ee,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x00007f35c882e933,Ptr{Void} @0x00007f35c882d7f0,Ptr{Void} @0x00007f35c882d5be,Ptr{Void} @0x00007f35c883a9e3,Ptr{Void} @0x00007f35c883a923,Ptr{Void} @0x00007f37ccfadf85,Ptr{Void} @0x00007f35c883a767,Ptr{Void} @0x00007f35c880f22d,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x00007f37ccffdc23,Ptr{Void} @0x00007f37ccffcfb9,Ptr{Void} @0x00007f37cd01034c,Ptr{Void} @0x00007f37cd010eec,Ptr{Void} @0x00007f37cd0110d8,Ptr{Void} @0x00007f37ca48e360,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x00007f35c8802d2b,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x00007f37ccffdc23,Ptr{Void} @0x00007f37ccffcfb9,Ptr{Void} @0x00007f37cd01034c,Ptr{Void} @0x00007f37cd0103c3,Ptr{Void} @0x00007f37ccfb6e60,Ptr{Void} @0x00007f35c880464a,Ptr{Void} @0x00007f35c880444a,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x00007f35c8803291,Ptr{Void} @0x00007f37cd010403,Ptr{Void} @0x00007f37cd010eec,Ptr{Void} @0x00007f37cd0110d8,Ptr{Void} @0x00007f37ca3cbda0,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x00007f35c8802d2b,Ptr{Void} @0x00007f37ccfadf85,Ptr{Void} @0x00007f37ca584ce4,Ptr{Void} @0x00007f37ca58341f,Ptr{Void} @0x00007f37ca584009,Ptr{Void} @0x00007f37ccfadeab,Ptr{Void} @0x0000000000401c27,Ptr{Void} @0x00000000004017af,Ptr{Void} @0x00007f37cbc4aec5,Ptr{Void} @0x00000000004017fd]))
call_basic ... OK
call_except ... OK
call_stm ... OK
eval_basic ... OK
eval_except ... OK
exportfn_basic ... OK
exportfn_except ... OK
exportfn_rec ... OK
importfn ... OK
marshalling_call ... OK
marshalling_eval ... OK
marshalling_except ... OK
proxyfn ... OK
ref_basic ... OK
ref_bind ... OK
ref_call ... OK
==============================[ ERROR: Polyglot ]===============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Polyglot/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: Polyglot had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:746
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:282
```

Then nothing happened. This happened from essentially just running `Pkg.test`. Have you even seen something like this? It didn't occur on Ubuntu Precise but I just updated to Ubuntu Trusy.

**Comment by wavexx** [comment] 2015-07-10 16:42
Like this no, but I'll have a look. Does "Expect" work for you now? Just to understand if this is something on the lower level (as I suspect).

**Comment by IainNZ** [comment] 2015-07-10 16:49
I haven't tried Expect again yet, but I imagine its related as no other package has this behavior.

**Comment by wavexx** [comment] 2015-07-13 20:08
I could reproduce this occasionally a couple of times, and indeed the problem lies within Expect.jl. It looks like some state in libuv is messed up during shutdown of the descriptors. As I need to manipulate some libuv/julia internal state, I need to recheck if some assumptions broke recently (note: I have pending patches that went into libuv 1.0, but AFAIK julia still hasn't moved to it).

**Comment by wavexx** [comment] 2017-04-05 17:17
Hi @IainNZ, I just pushed Expect 0.2.0: https://github.com/JuliaLang/METADATA.jl/pull/8699

The tty hack I was doing is no longer required with julia 0.5+ as it has been integrated with libuv 1.0.
Can you re-enable testing for both Expect and Polyglot? Should we wait until the PR is merged?

I expect Polyglot to fail, since it hasn't been updated for the new Expect interface, but it shouldn't hang anymore.

**Comment by wavexx** [comment] 2017-04-06 09:28
It's in.

**Comment by wavexx** [comment] 2017-04-16 22:59
This is now fixed

**Closed as completed by wavexx** 2017-04-16 22:59 UTC
